version: "3"

services:
  restaraunt-life-challenge-react:
    container_name: restaraunt-life-challenge-reactjs
    build: ./frontend/
    volumes:
      - /usr/src/app/node_modules
    ports:
      - 3000:3000

  restaurant-life-challenge-node:
    container_name: restaurant-life-challenge-nodejs
    build: ./backend/
    volumes:
      - ./backend/:/usr/app
      - /usr/app/node_modules
    command: sh -c "yarn && yarn dev"
    depends_on:
      - postgres
    networks:
      - app-connect
    ports:
      - "3333:3333"

  postgres:
    container_name: "postgresql-restaurant"
    image: postgres:11
    restart: unless-stopped
    volumes:
      - postgres-restaurant-data:/data
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - app-connect
    ports:
      - "5432:5432"
volumes:
  postgres-restaurant-data:

networks:
  app-connect:
    driver: bridge
