version: '3'

services:
  restaurant-life-challenge:
    container_name: restaurant-life-challenge-node
    build: '.'
    volumes:
      - .:/usr/app
    depends_on:
      - postgres
    networks:
      - app-connect
    ports:
      - '3333:3333'

  postgres:
    container_name: 'postgres-restaurant'
    image: postgres:11
    restart: unless-stopped
    volumes:
      - postgres-restaurant-data:/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - app-connect
    ports:
      - '5432:5432'
volumes:
  postgres-restaurant-data:

networks:
  app-connect:
    driver: bridge
